project/urls.py
from django.contrib import admin
from django.urls import path,include
from base.views import home,contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('sklep/', include('shop.urls')),
    path('kontakt/', contact, name="contact"),
]

shop/urls.py
from django.urls import path
from .views import home,payment

app_name = "shop"

urlpatterns = [
    path('', home, name="home"),
    path('platnosc/<product>', payment, name="payment"),
]

base/models.py
from django.db import models
from django import forms

from captcha.fields import ReCaptchaField

topics = (
    ('payment', 'Płatność'),
    ('server', 'Usprawnienie servera.'),
    ('rofl', 'Admin daj moda.'),
    ('other', 'Inne.'))

class messageModel(models.Model):
    name    = models.CharField(max_length=30)
    email   = models.EmailField()
    topic   = models.CharField(max_length=30)
    message = models.TextField()

class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField()

shop/models.py
from django.db import models

class paymentModel(models.Model):
    active      = models.BooleanField(default=True)
    name        = models.CharField(max_length=30)
    email       = models.EmailField()
    message     = models.TextField()
    time        = models.DateField(auto_now_add=True)

base/views.py
from django.shortcuts import render,redirect
from django.core.mail import EmailMessage
from .models import messageModel, FormWithCaptcha

import yagmail

topics = {
        'payment':  'Płatność',
        'server':   'Usprawnienie servera.',
        'rofl':     'Admin daj moda.',
        'other':    'Inne.',
    }

def send_email(emailTo,name,emailFrom,topic,message):

    message = f"<h1>McUtopia.fun - SERVER</h1><h2>Temat: {topic}</h2><h3>Od {name}, {emailFrom}</h3><p>{message}</p>"
    yag = yagmail.SMTP(user='', password='')

    yag.send(to=emailTo, subject=topic, contents=message)
    print("Email sent successfully")

def home(request):
    return render(request,'base/home.html')

def contact(request):

    if request.method == 'POST':

        name    = request.POST.get('name')
        email   = request.POST.get('email')
        topic   = request.POST.get('topic')
        message = request.POST.get('message')
        
        Form = FormWithCaptcha(request.POST)
        if (email and topic and message) is not None and Form.is_valid():
            topic = topics.get(topic,"Nieprawidłowy temat.")

            print(name, email,topic,message)
            x = messageModel(name=name,email=email,topic=topic,message=message)
            x.save()

            send_email('',name,email,topic,message)
            return redirect(home)
    
    return render(request,'base/contact.html',{'captcha': FormWithCaptcha})

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from base.models import FormWithCaptcha
from .models import paymentModel

import yagmail

products = [
    'vip','sponsor','kozak'
]


def send_email(emailTo,name,emailFrom,topic,message,product):

    message = f"<h1>McUtopia.fun - SERVER</h1><h2>Temat: {topic} </h2><h3>Nazwa Minecraft - {name}</h3><h3>Email - {emailFrom}</h3><h3>Produkt - {product}</h3><p>{message}</p>"
    yag = yagmail.SMTP(user='', password='')

    yag.send(to=emailTo, subject=topic, contents=message)
    print("Email sent successfully")

def home(request):
    return render(request,'shop/home.html')

def payment(request,product):
    if product in products:
        if request.method == 'POST':

            name    = request.POST.get('name')
            email   = request.POST.get('email')
            message = request.POST.get('message')
            
            Form = FormWithCaptcha(request.POST)
            if (email and name) is not None and Form.is_valid():
                
                x = paymentModel(name=name,email=email,message=message)
                x.save()

                topic = 'Zamówienie #' + str(x.pk) 
                print(name, email,topic,message)

                send_email('',name,email,topic,message,product)

                context = {
                    'payment_number': topic
                }
                
                return render(request,'shop/payment_succes.html',context)
            else:
                return HttpResponse("Coś poszło nie tak, spróbuj ponownie")
        else:
            return render(request,'shop/payment.html',{'product':product,'captcha': FormWithCaptcha})
    else:
        return HttpResponse("Nie mamy takiego produktu ?")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Sebastian Ozimkowski">
    <meta name="keywords"
        content="minecraft, server, serverminecraft, mcutopia, najlepszy server, survival, szybkie pytanie natury egzystencjalnej Dokąd zmierza ten server?, mcutopia.fun, mcutopia.csrv.pl">
    <meta name="description"
        content='Server community "Szybkie pytanie natury egzystencjalnej, Dokąd zmierza ten server?"'>

    <title>McUtopia.fun - Najlepszy server minecraft</title>

    <link rel="icon" type="image/png" href="{% static '/img/favicon.ico' %}" />

    <!-- STYLE -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- JS -->
    <script src="https://kit.fontawesome.com/" crossorigin="anonymous"></script>

    {% block 'head' %}
    {% endblock%}

</head>

<body>
    <div class="notloaded"></div>
    <nav class="mobile_navigation">
        <div class="hero is-fullheight">
            <div class="hero-body ">
                <div class="container is-centered is-horizontal-center">
                    <a href="{% url 'home' %}" class="navbar-item">Strona Główna</a>
                    <a href="{% url 'shop:home' %}" class="navbar-item">Sklep</a>
                    <a href="{% url 'contact' %}" class="navbar-item">Kontakt</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="hero is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand is-large">
                        <div class="flex-row">
                            <a href="{% url 'home' %}">
                                <img class="image is-48x48" src="{% static 'img/logo.jpg'%}" alt="Logo">
                            </a>       
                            <h1 class="is-large ml-4 is-size-4"><a href="{% url 'home' %}">McUtopia.fun</a></h1>                                        
                        </div>

                        <a class="navbar-burger burger" onclick="menu()" data-target="navbarMenuHeroA">
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                        </a>
                    </div>
                    <div class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{% url 'home' %}" class="navbar-item underline">Strona Główna</a>
                            <a href="{% url 'shop:home' %}" class="navbar-item underline">Sklep</a>
                            <a href="{% url 'contact' %}" class="navbar-item underline">Kontakt</a>
                            <span class="navbar-item">
                                <a href="https://discord.gg/" class="button is-info" onclick="menu()">
                                    <span class="icon">
                                        <i class="fab fa-discord"></i>
                                    </span>
                                    <span>Discord</span>
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            {% block content %}
            {% endblock %}
        </div>
    </section>
    <script src="https://skrypt-cookies.pl/id/5272f46bd393f458.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

templates/base/contact.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'css/contact.css' %}"> 
{% endblock %}

{% block content %}
<div class="container columns is-gapless">
    <div class="column contact">
        <h2 class="title pt-5 pb-5">Formularz kontaktowy</h2>
        <p class="subtitle">Wyślij nam wiadomość, <strong><a href="mailto:sebastianfejsbuk@gmail.com">tutaj</a></strong> lub bezpośrednio poniżej</p>
        <form method="POST" >{% csrf_token %}
            <label class="label pt-1">Twoje piękne imię :)</label>
            <input class="input" name="name" type="text" placeholder="np. Adolf">
            <label class="label pt-1">Twój email</label>
            <input class="input" name="email" type="email" placeholder="np. severussnape@hogwart.com">
            <label class="label pt-1">Temat</label>
            <div class="control">
                <div class="select">
                <select name="topic">
                    <option value="payment">Płatność</option>
                    <option value="server">Usprawnienie servera.</option>
                    <option value="rofl">Admin daj moda.</option>
                    <option value="other">Inne.</option>
                </select>
                </div>
            </div>
            <label class="label pt-1">Treść wiadmości</label>
            <textarea name="message" class="textarea has-fixed-size pb-3" placeholder="Admin daj moda."></textarea>
            {{captcha}}
            <div class="pt-3 pb-3 ">
                <button class="button is-link ">Wyślij</button>
            </div>
        </form>
    </div>
    <figure class="column  is-three-fifths is-gapless">
        <img class="image is-vcentered" src="{% static '/img/1.jpg'%}" alt="zdjęcie z spawna gry">
    </figure>
</div>
{% endblock %}

templates/base/home.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}"> 
{% endblock %}

{% load static %}
{% block content %}
<div class="container columns is-gapless">
  <div class="column">
    <h2 class="title pt-5 pb-5">Witaj na McUtopia.fun</h2>
    <p class="subtitle is-5 mb-2">Szybkie pytanie natury egzystencjalnej<br>Dokąd zmierza ten server?</p>
    <div class="data">
      <a class="ip" onclick="fallbackCopyTextToClipboard('mcutopia.csrv.pl')">
        <p class="subtitle is-medium has-text-success-dark mb-1">IP - mcutopia.csrv.pl</p>
        <span class="tag is-warning is-light">
          <- Kopiuj! </span>
      </a>
      <a href="https://discord.gg/ZDtKd7C" class="subtitle is-6 has-text-link-dark">DC
        - https://discord.gg/</a>
    </div>
    <h3 class="title pt-5 pb-5">Znajdź nas na <a href="https://www.facebook.com/groups/985996681745216"
        target="_blank" rel="noopener"><strong>Facebooku!</strong></a></h3>
  </div>
  <div class="column is-three-fifths">
    <img src="{% static '/img/1.jpg'%}" alt="zdjęcie z spawna gry">
  </div>
</div>
{% endblock %}

templates/shop/home.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'css/extensions/bulma-pricingtable.min.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="section are-large">
        <h2 class="title">Utopijny sklep.</h2>
        <p class="subtitle">Wybierz usługę i przejdź do płatności </p>
        
        <div class="pricing-table is-horizontal">
            <div class="pricing-plan">
              <div class="plan-header">VIP</div>
              
              <div class="plan-items">
                <div class="plan-item">Ranga na Discordzie</div>
                <div class="plan-item">Możliwość pisania kolorem</div>
                <div class="plan-item">5Diaxów codziennie</div>
                <div class="plan-item">Fly</div>
                <div class="plan-item">-</div>
                <div class="plan-item">-</div>
              </div>
              <div class="plan-footer">
                    <div class="plan-price"><span class="plan-price-amount has-text-primary-dark"><span class="plan-price-currency">Zł</span>15</span>/Miesiąc</div>
                    <a href="{% url 'shop:payment' 'vip' %}">
                        <button class="button is-fullwidth has-background-primary-dark has-text-white-bis" onclick="payment()">Dalej</button>
                    </a>
                </div>
            </div>
          
            <div class="pricing-plan">
                <div class="plan-header">Sponsor</div>
                
                <div class="plan-items">
                  <div class="plan-item">Ranga na Discordzie</div>
                  <div class="plan-item">Możliwość pisania kolorem</div>
                  <div class="plan-item">5Diaxów codziennie</div>
                  <div class="plan-item">Fly</div>
                  <div class="plan-item">Big dick</div>
                  <div class="plan-item">-</div>
                </div>
                <div class="plan-footer">
                    <div class="plan-price"><span class="plan-price-amount has-text-link-dark"><span class="plan-price-currency">Zł</span>30</span>/Miesiąc</div>
                    <a href="{% url 'shop:payment' 'sponsor' %}">
                        <button class="button is-fullwidth has-background-link-dark has-text-white-bis">Dalej</button>
                    </a>
                </div>
              </div>
          
            <div class="pricing-plan">
              <div class="plan-header">Kozak Totalny</div>
              <div class="plan-items">
                <div class="plan-item">Ranga na Discordzie</div>
                <div class="plan-item">Możliwość pisania kolorem</div>
                <div class="plan-item">5Diaxów codziennie</div>
                <div class="plan-item">Fly</div>
                <div class="plan-item">Big dick</div>
                <div class="plan-item">-</div>
              </div>
              <div class="plan-footer">
                <div class="plan-price"><span class="plan-price-amount has-text-danger-dark"><span class="plan-price-currency">Zł</span>100</span>/Miesiąc</div>
                <a href="{% url 'shop:payment' 'kozak' %}">
                    <button class="button is-fullwidth has-background-danger-dark has-text-white-bis">Dalej</button>
                </a>
              </div>
            </div>
          </div>

    </div>
</div>

{% endblock %}

templates/shop/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container columns is-gapless">
    <div class="column contact">
        <h2 class="title pt-5 pb-5">Płatność za "{{product.capitalize}}"</h2>
        <p class="subtitle">Dziękujemy ,że nas wspierasz!</p>
        <form method="POST">{% csrf_token %}
            <label class="label">Nazwa użytkownika na Serverze</label>
            <input class="input" name="name" type="text" placeholder="Ziobro2007">
            <label class="label pt-1">Twój email</label>
            <input class="input" name="email" type="email" placeholder="np. severussnape@hogwart.com">
            <label class="label pt-1">Dodatkowa wiadomość</label>
            <textarea class="textarea has-fixed-size pb-3" name="message" placeholder="Jeśli nic nie potrzebujesz zostaw puste."></textarea>
            {{captcha}}
            <div class="pt-3 pb-3 ">
                <button class="button is-link ">Płacę</button>
            </div>
        </form>
    </div>
    <figure class="column  is-three-fifths is-gapless">
        <img class="image is-vcentered" src="{% static '/img/1.jpg'%}" alt="zdjęcie z spawna gry">
    </figure>
</div>
{% endblock %}

templates/shop/payment_succes.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container columns is-gapless">
    <div class="column contact">
        <h2 class="title pt-5">Zamówienie w realizacji</h2>
        <p class="subtitle">Dziękujemy ,że nas wspierasz!</p>
        <p class="subtitle">
        Dziękujemy ,że nas wspierasz!<br>
        Wyślij zamówienie z tytułem: "{{payment_number}}"<br>
        Zamówienie zrealizujemy w ciągu 24 godzin.
        </p>
    </div>
    <figure class="column  is-three-fifths is-gapless">
        <img class="image is-vcentered" src="{% static '/img/1.jpg'%}" alt="zdjęcie z spawna gry">
    </figure>
</div>
{% endblock %}